# Nombre del buildpack
name = "whatsapp-manager-backend"

# Versión del buildpack
version = "0.1.1"

# Dependencias del buildpack
dependencies = [
  "npm@latest"
]

# Pasos del buildpack
[[buildpack.buildpacks]]
id = "npm"
version = "latest"

[[buildpack.buildpacks]]
id = "node-modules"
version = "latest"

# Comando para ejecutar la API
[[buildpack.run]]
command = "node ./src/index.js"