# Nombre y versión del buildpack
name = "whatsapp-manager-backend"
version = "2023.11.16t3"

# Dependencias del buildpack
dependencies = [
  "nodejs"
]

[[buildpacks]]
id = "fl0/nodejs"
version = "18.x"  # Especifica la versión de Node.js que necesites, por ejemplo "14.x"

# Comando para ejecutar la API
[[run]]
command = "npm start"
