# Nombre y versión del buildpack
name = "whatsapp-manager-backend"
version = "2023.11.14t1"

# Dependencias del buildpack
dependencies = [
  "npm@latest"
]

# Buildpacks necesarios
[[buildpacks]]
id = "nodejs"
version = "latest"

[[buildpacks]]
id = "npm"
version = "latest"

[[buildpack.buildpacks]]
id = "node-modules"
version = "latest"

# Comando para ejecutar la API
[[run]]
command = "npm start"

# Comando para ejecutar la API
[[buildpack.run]]
command = "node ./src/index.js"