# Nombre y versión del buildpack
name = "whatsapp-manager-backend"
version = "2023.11.16t3"

# Dependencias del buildpack
dependencies = [
  "nodejs"
]

[[run]]
command = "npm start"

[[buildpacks]]
  id = "fl/heroku/nodejs"

[[buildpacks]]
  id = "fl/heroku/npm"

[build]
  command = "npm install"

[dev]
  command = "npm run dev"

[web]
  command = "npm start"